/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lecture_code;

public class App {
    public String getGreeting(int n) {

        String greeting = "Hello";

        for(int i = 0; i < n ; i++){
            greeting += "o";
        }
        
        return greeting +" World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting(7));
    }
}
